<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>14.8 Promise.reject</title>
</head>
<body>
    <script>
        //Promise.reject(reason)方法也会返回一个新的Promise实例,状态为Rejected
        var p=new Promise((resolve,reject)=>reject('warning'));
        p.then(null,function(s){
            console.log(s);
        });
        //上面的代码生成一个Promise对象的实例p,状态为Rejected,回调函数会立即执行.
        /**
        *注意:Promise.reject()方法的参数会原封不动地作为reject的理由变成后续方法的参数
            这一点与Promise.resolve方法不一致
        **/

        const thenable={
            then(resolve,reject){
                reject('warning')
            }
        };
        Promise.reject(thenable).catch(e=>console.log(e===thenable))    //true

        //上面的代码中,Promise.reject方法的参数是一个thenable对象
        //执行以后,后面catch方法的参数不是reject抛出的'warning'这个字符串,而是thenable对象

        
    </script>
</body>
</html>